### PR TITLE
Added additional settings options for APNS and GCM and also added optional settings for Web (Chrome,Firefox etc.) to support the latest Push Server features

### PR DESCRIPTION
**Pull request by ManavIBM**
Added additional settings options for APNS and GCM and also added optional settings for Chrome ,ChromAppExt , Firefox and Safari with the latest features as supported by the Push Server Code.

https://mobile.ng.bluemix.net/imfpush/

### CODE REVIEW

**Comment by neekrish** [comment]
Please provide a more meaningful heading and also describe in the PR what's new and what's changing and what needs review please. It help us get started

**Review by neekrish — CHANGES_REQUESTED** [review]
See comments

**Comment by ManavIBM** [comment]
@neekrish  Update heading and provided a description comment.

**Review by neekrish — CHANGES_REQUESTED** [review]
1. No backward compatibility :  Not required as discussed with Shrinu.
2. Image URL change : done
3. javadoc to be developed: done
4. Cotructive example
timeToLive : done
PushNotificationsPlatform: 
1.  to Platform: done
an optional ResponseListener  <- Not optional
ResponseListener <- Example : done

Exception - To specific exception : done
throw new IllegalArgumentException(PushConstants.ALERT_NOT_NULL_EXCEPTIOPN); - > Exception spelling : done

443 -> Not required : done

Ensure local or dedicated is supported - override host: done

CONTENTTYPE CONTENT_TYPE: done

Test with 1.6 java: done

**Comment by neekrish** [comment]
Updated @ManavIBM about more changes to be done

**Comment by vishalpalliyathu** [comment]
@ManavIBM .., I shall open a task for the doc review, as I dont have review access and the scope of the work is rather large. 

Referenced to https://github.ibm.com/bluemix-mobile-services/bmd-project-push/issues/1253

**Pull request closed without merging**
